"""add payroll item source

Revision ID: 3af9a071b5e1
Revises: 47b6d2540510
Create Date: 2026-08-03 15:40:29.111693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af9a071b5e1'
down_revision: Union[str, Sequence[str], None] = '47b6d2540510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('erp_payroll_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='timesheet', nullable=False))

    # The default backfills every existing row as 'timesheet', which is wrong
    # for rows that no timesheet could have produced. A run whose month holds
    # no work entries for its company was typed in by hand -- that is how the
    # 2025 payroll imported from the paper vouchers got here -- and marking it
    # 'timesheet' would freeze exactly the figures somebody may need to correct.
    #
    # Decided per run rather than blanket-updating, so this stays correct on a
    # database that does have timesheet-generated runs.
    op.execute("""
        UPDATE erp_payroll_items SET source = 'manual'
        WHERE run_id IN (
            SELECT r.id FROM erp_payroll_runs r
            WHERE NOT EXISTS (
                SELECT 1 FROM erp_work_entries w
                WHERE w.company = r.company
                  AND w.work_date BETWEEN r.period_start AND r.period_end
            )
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_payroll_items', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
