"""add payroll runs and items

Revision ID: 47b6d2540510
Revises: a935a6328250
Create Date: 2026-08-03 14:17:58.232080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b6d2540510'
down_revision: Union[str, Sequence[str], None] = 'a935a6328250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_payroll_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('statutory_basis', sa.Text(), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'period', name='uq_erp_payroll_runs_company_period')
    )
    with op.batch_alter_table('erp_payroll_runs', schema=None) as batch_op:
        batch_op.create_index('idx_erp_payroll_runs_period', ['period'], unique=False)

    op.create_table('erp_payroll_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('employee_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=64), server_default='', nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('ot_rule', sa.String(length=255), server_default='', nullable=False),
    sa.Column('bank_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('bank_account_no', sa.String(length=64), server_default='', nullable=False),
    sa.Column('epf_member_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('socso_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('day_units', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('ot_hours', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('overnight_nights', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('overnight_hours', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('normal_pay', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('ot_pay', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('overnight_pay', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('fixed_allowance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('adjustment', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('adjustment_note', sa.String(length=255), server_default='', nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('epf_employee', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('epf_employer', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('socso_employee', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('socso_employer', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('eis_employee', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('eis_employer', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('pcb', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('other_deduction', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('other_deduction_note', sa.String(length=255), server_default='', nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['erp_employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['erp_payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'employee_id', name='uq_erp_payroll_items_run_employee')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_payroll_items')
    with op.batch_alter_table('erp_payroll_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_payroll_runs_period')

    op.drop_table('erp_payroll_runs')
    # ### end Alembic commands ###
