"""add document inbox

Revision ID: 4b68c4f3f0d9
Revises: 3af9a071b5e1
Create Date: 2026-08-04 16:13:02.016523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b68c4f3f0d9'
down_revision: Union[str, Sequence[str], None] = '3af9a071b5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), server_default='', nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('preview_path', sa.String(length=255), server_default='', nullable=False),
    sa.Column('mime_type', sa.String(length=64), server_default='', nullable=False),
    sa.Column('byte_size', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error_text', sa.Text(), server_default='', nullable=False),
    sa.Column('doc_class', sa.String(length=24), server_default='unclassified', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='0', nullable=False),
    sa.Column('issuer', sa.String(length=255), server_default='', nullable=False),
    sa.Column('bill_to', sa.String(length=255), server_default='', nullable=False),
    sa.Column('doc_no', sa.String(length=64), server_default='', nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default='', nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('summary', sa.String(length=500), server_default='', nullable=False),
    sa.Column('raw_json', sa.Text(), server_default='', nullable=False),
    sa.Column('duplicate_of', sa.String(length=32), nullable=True),
    sa.Column('model_used', sa.String(length=64), server_default='', nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['erp_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'sha256', name='uq_erp_documents_company_sha256')
    )
    with op.batch_alter_table('erp_documents', schema=None) as batch_op:
        batch_op.create_index('ix_erp_documents_company_class', ['company', 'doc_class'], unique=False)
        batch_op.create_index('ix_erp_documents_company_uploaded', ['company', 'uploaded_at'], unique=False)
        batch_op.create_index('ix_erp_documents_dupe', ['company', 'issuer', 'doc_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_documents_duplicate_of'), ['duplicate_of'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_documents_duplicate_of'))
        batch_op.drop_index('ix_erp_documents_dupe')
        batch_op.drop_index('ix_erp_documents_company_uploaded')
        batch_op.drop_index('ix_erp_documents_company_class')

    op.drop_table('erp_documents')
    # ### end Alembic commands ###
