"""add employees

Revision ID: 54a69eb60389
Revises: 22688ded425d
Create Date: 2026-08-01 11:34:18.566127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a69eb60389'
down_revision: Union[str, Sequence[str], None] = '22688ded425d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_employees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=64), server_default='', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='', nullable=False),
    sa.Column('ic_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('hired_on', sa.Date(), nullable=True),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='Active', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['username'], ['erp_users.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code', name='uq_erp_employees_code'),
    sa.UniqueConstraint('username', name='uq_erp_employees_username')
    )
    with op.batch_alter_table('erp_employees', schema=None) as batch_op:
        batch_op.create_index('idx_erp_employees_status_name', ['status', 'name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_employees', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_employees_status_name')

    op.drop_table('erp_employees')
    # ### end Alembic commands ###
