"""keep document ocr text

Revision ID: 5731f451ac52
Revises: 4b68c4f3f0d9
Create Date: 2026-08-05 13:19:56.369904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5731f451ac52'
down_revision: Union[str, Sequence[str], None] = '4b68c4f3f0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_documents', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')

    # ### end Alembic commands ###
