"""add employee salary setup

Revision ID: 5be2a3235d58
Revises: 54a69eb60389
Create Date: 2026-08-01 13:57:56.783362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be2a3235d58'
down_revision: Union[str, Sequence[str], None] = '54a69eb60389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_employee_salary',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('pay_type', sa.String(length=16), server_default='Monthly', nullable=False),
    sa.Column('basic_rate', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('fixed_allowance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('allowance_note', sa.String(length=255), server_default='', nullable=False),
    sa.Column('epf_member_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('socso_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('tax_no', sa.String(length=32), server_default='', nullable=False),
    sa.Column('epf_contributing', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('socso_contributing', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('bank_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('bank_account_no', sa.String(length=64), server_default='', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['erp_employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_employee_salary')
    # ### end Alembic commands ###
