"""baseline: ERP-owned schema

Revision ID: 8cc3e9a9bd3f
Revises: 
Create Date: 2026-08-01 10:02:06.616341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc3e9a9bd3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('debtor_code', sa.String(length=64), server_default='', nullable=False),
    sa.Column('debtor_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('contact_person', sa.String(length=128), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=64), server_default='', nullable=False),
    sa.Column('site_address', sa.Text(), server_default='', nullable=False),
    sa.Column('service_category', sa.String(length=64), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='Lead', nullable=False),
    sa.Column('expected_install_date', sa.String(length=20), server_default='', nullable=False),
    sa.Column('completion_date', sa.String(length=20), server_default='', nullable=False),
    sa.Column('quoted_total', sa.Float(), nullable=True),
    sa.Column('collected_total', sa.Float(), nullable=True),
    sa.Column('outstanding_amount', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'project_code', name='uq_erp_projects_company_code')
    )
    with op.batch_alter_table('erp_projects', schema=None) as batch_op:
        batch_op.create_index('idx_erp_projects_company_updated', ['company', 'updated_at'], unique=False)

    op.create_table('erp_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('database_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('server', sa.String(length=128), server_default='', nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('erp_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_erp_sessions_expires_at', ['expires_at'], unique=False)

    op.create_table('erp_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('default_company', sa.String(length=64), server_default='', nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('erp_website_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('project_code', sa.String(length=64), server_default='', nullable=False),
    sa.Column('field_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('old_value', sa.Text(), server_default='', nullable=False),
    sa.Column('new_value', sa.Text(), server_default='', nullable=False),
    sa.Column('username', sa.String(length=64), server_default='', nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erp_website_audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_erp_website_audit_company_created', ['company', 'created_at'], unique=False)

    op.create_table('sengchong_contacts',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('bg', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('sengchong_services',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('bg', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('sengchong_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('erp_project_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('doc_no', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['erp_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'module', 'doc_no', name='uq_erp_project_documents_link')
    )
    with op.batch_alter_table('erp_project_documents', schema=None) as batch_op:
        batch_op.create_index('idx_erp_project_documents_lookup', ['module', 'doc_no'], unique=False)

    op.create_table('erp_project_photos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), server_default='', nullable=False),
    sa.Column('content_type', sa.String(length=64), server_default='image/jpeg', nullable=False),
    sa.Column('original_filename', sa.String(length=255), server_default='', nullable=False),
    sa.Column('service_category', sa.String(length=64), server_default='', nullable=False),
    sa.Column('caption', sa.Text(), server_default='', nullable=False),
    sa.Column('alt_text', sa.Text(), server_default='', nullable=False),
    sa.Column('is_public', sa.Integer(), server_default='0', nullable=False),
    sa.Column('website_visible', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_cover', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['erp_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erp_project_photos', schema=None) as batch_op:
        batch_op.create_index('idx_erp_project_photos_project', ['project_id', 'sort_order', 'created_at'], unique=False)
        batch_op.create_index('idx_erp_project_photos_public', ['company', 'is_public', 'website_visible', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_project_photos', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_project_photos_public')
        batch_op.drop_index('idx_erp_project_photos_project')

    op.drop_table('erp_project_photos')
    with op.batch_alter_table('erp_project_documents', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_project_documents_lookup')

    op.drop_table('erp_project_documents')
    op.drop_table('sengchong_settings')
    op.drop_table('sengchong_services')
    op.drop_table('sengchong_contacts')
    with op.batch_alter_table('erp_website_audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_website_audit_company_created')

    op.drop_table('erp_website_audit_log')
    op.drop_table('erp_users')
    with op.batch_alter_table('erp_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_sessions_expires_at')

    op.drop_table('erp_sessions')
    with op.batch_alter_table('erp_projects', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_projects_company_updated')

    op.drop_table('erp_projects')
    # ### end Alembic commands ###
