"""add work entries and overtime rules

Revision ID: a935a6328250
Revises: 5be2a3235d58
Create Date: 2026-08-01 16:18:49.414750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a935a6328250'
down_revision: Union[str, Sequence[str], None] = '5be2a3235d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_work_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('day_units', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('ot_hours', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('overnight_nights', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('overnight_hours', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), server_default='', nullable=False),
    sa.Column('updated_by', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['erp_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['erp_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erp_work_entries', schema=None) as batch_op:
        batch_op.create_index('idx_erp_work_entries_date_company', ['work_date', 'company'], unique=False)
        batch_op.create_index('idx_erp_work_entries_employee_date', ['employee_id', 'work_date'], unique=False)
        batch_op.create_index('idx_erp_work_entries_project', ['project_id'], unique=False)

    with op.batch_alter_table('erp_employee_salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ot_divisor', sa.Numeric(precision=5, scale=2), server_default='8', nullable=False))
        batch_op.add_column(sa.Column('ot_multiplier', sa.Numeric(precision=5, scale=2), server_default='1.5', nullable=False))
        batch_op.add_column(sa.Column('overnight_mode', sa.String(length=24), server_default='allowance', nullable=False))
        batch_op.add_column(sa.Column('overnight_allowance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('overnight_multiplier', sa.Numeric(precision=5, scale=2), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('overnight_day_factor', sa.Numeric(precision=5, scale=2), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_employee_salary', schema=None) as batch_op:
        batch_op.drop_column('overnight_day_factor')
        batch_op.drop_column('overnight_multiplier')
        batch_op.drop_column('overnight_allowance')
        batch_op.drop_column('overnight_mode')
        batch_op.drop_column('ot_multiplier')
        batch_op.drop_column('ot_divisor')

    with op.batch_alter_table('erp_work_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_erp_work_entries_project')
        batch_op.drop_index('idx_erp_work_entries_employee_date')
        batch_op.drop_index('idx_erp_work_entries_date_company')

    op.drop_table('erp_work_entries')
    # ### end Alembic commands ###
