import {
  Banknote,
  CalendarClock,
  ClipboardList,
  Contact,
  FileText,
  Image as ImageIcon,
  Package,
  ReceiptText,
  ShieldCheck,
  ShoppingCart,
  Users,
} from "lucide-react";
import {
  EMPLOYEE_POSITIONS,
  EMPLOYEE_STATUSES,
  MONEY,
  OVERNIGHT_MODES,
  PAY_TYPES,
  PROJECT_SERVICE_CATEGORIES,
  PROJECT_STATUSES,
  QTY,
  today,
} from "./constants.js";

export const MODULES = {
  projects: {
    title: "Projects",
    editable: true,
    singular: "Project",
    label: "Projects",
    meta: "Seng Chong jobs",
    icon: ClipboardList,
    createLabel: "New Project",
    rowKey: "projectCode",
    columns: [
      ["projectCode", "Project"],
      ["title", "Title"],
      ["debtorName", "Customer"],
      ["serviceCategory", "Category"],
      ["status", "Status"],
      ["quotationDocNosText", "Quotation"],
      ["invoiceDocNosText", "Invoice"],
      ["quotedTotal", "Quoted", "money"],
      ["collectedTotal", "Paid", "money"],
      ["outstandingAmount", "Outstanding", "money"],
      ["actualCost", "Cost", "money"],
      ["margin", "Margin", "money"],
      ["expectedInstallDate", "Install Date"],
    ],
    detailFields: [
      ["projectCode", "Project"],
      ["title", "Title"],
      ["status", "Status"],
      ["serviceCategory", "Category"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Debtor Name"],
      ["contactPerson", "Contact"],
      ["phone", "Phone"],
      ["siteAddress", "Site Address"],
      ["quotationDocNosText", "Quotation"],
      ["invoiceDocNosText", "Invoice"],
      ["purchaseOrderDocNosText", "Purchase Orders"],
      ["arPaymentDocNosText", "AR Payments"],
      ["apInvoiceDocNosText", "AP Invoices"],
      ["expectedInstallDate", "Expected Install"],
      ["completionDate", "Completed"],
      ["quotedTotal", "Quoted", "money"],
      ["collectedTotal", "Collected", "money"],
      ["outstandingAmount", "Outstanding", "money"],
      ["estimatedCost", "Estimated Cost", "money"],
      ["actualCost", "Actual Cost", "money"],
      ["margin", "Margin", "money"],
      ["notes", "Notes"],
    ],
    detailLineColumns: [],
    formFields: [
      { name: "title", label: "Project Title", required: true, span: 2 },
      { name: "status", label: "Status", type: "select", options: PROJECT_STATUSES },
      { name: "debtorCode", label: "Debtor Code" },
      { name: "debtorName", label: "Debtor Name" },
      {
        name: "serviceCategory",
        label: "Service Category",
        type: "select",
        options: PROJECT_SERVICE_CATEGORIES,
      },
      { name: "contactPerson", label: "Contact Person" },
      { name: "phone", label: "Phone" },
      { name: "siteAddress", label: "Site Address", span: 2 },
      { name: "quotationDocNo", label: "Quotation Doc No" },
      { name: "invoiceDocNo", label: "Invoice Doc No" },
      { name: "purchaseOrderDocNos", label: "Purchase Order Nos", span: 2 },
      { name: "arPaymentDocNos", label: "AR Payment Nos", span: 2 },
      { name: "apInvoiceDocNos", label: "AP Invoice Nos", span: 2 },
      { name: "expectedInstallDate", label: "Expected Install", type: "date" },
      { name: "completionDate", label: "Completed", type: "date" },
      { name: "quotedTotal", label: "Quoted Total", ...MONEY },
      { name: "collectedTotal", label: "Collected Total", ...MONEY },
      { name: "outstandingAmount", label: "Outstanding", ...MONEY },
      { name: "estimatedCost", label: "Estimated Cost", ...MONEY },
      { name: "actualCost", label: "Actual Cost", ...MONEY },
      { name: "notes", label: "Notes", type: "textarea", span: 2, rows: 3 },
    ],
    lineFields: [],
    payload: () => ({
      title: "",
      status: "Lead",
      debtorCode: "",
      debtorName: "",
      serviceCategory: PROJECT_SERVICE_CATEGORIES[0],
      contactPerson: "",
      phone: "",
      siteAddress: "",
      quotationDocNo: "",
      invoiceDocNo: "",
      purchaseOrderDocNos: "",
      arPaymentDocNos: "",
      apInvoiceDocNos: "",
      expectedInstallDate: "",
      completionDate: "",
      quotedTotal: "",
      collectedTotal: "",
      outstandingAmount: "",
      estimatedCost: "",
      actualCost: "",
      notes: "",
      lines: [],
    }),
  },
  invoices: {
    title: "Invoices",
    singular: "Invoice",
    label: "Invoices",
    meta: "AR invoice",
    icon: FileText,
    createLabel: "New Draft",
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Name"],
      ["description", "Description"],
      ["total", "Total", "money"],
      ["netTotal", "Net Total", "money"],
      ["paymentAmt", "Paid", "money"],
      ["outstanding", "Outstanding", "money"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["dueDate", "Due Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Debtor Name"],
      ["description", "Description"],
      ["journalType", "Journal"],
      ["currencyCode", "Currency"],
      ["currencyRate", "Rate", "number"],
      ["total", "Total", "money"],
      ["netTotal", "Net Total", "money"],
      ["paymentAmt", "Paid", "money"],
      ["outstanding", "Outstanding", "money"],
      ["status", "Status"],
      ["cancelled", "Cancelled"],
    ],
    detailLineColumns: [
      ["seq", "Seq"],
      ["accNo", "Account"],
      ["description", "Description"],
      ["amount", "Amount", "number"],
      ["taxCode", "Tax"],
      ["netAmount", "Net", "number"],
    ],
    formFields: [
      { name: "debtorCode", label: "Debtor Code", required: true },
      { name: "docDate", label: "Doc Date", type: "date" },
      { name: "dueDate", label: "Due Date", type: "date" },
      { name: "description", label: "Description", span: 2 },
      { name: "journalType", label: "Journal Type" },
      { name: "currencyRate", label: "Currency Rate", ...MONEY },
      { name: "inclusiveTax", label: "Inclusive Tax", type: "checkbox" },
    ],
    lineFields: [
      { name: "accNo", label: "Sales Account", required: true },
      { name: "description", label: "Description", span: 2 },
      { name: "amount", label: "Amount", ...MONEY },
      { name: "taxCode", label: "Tax Code" },
      { name: "projNo", label: "Project" },
      { name: "deptNo", label: "Dept" },
    ],
    payload: () => ({
      debtorCode: "300-U001",
      docDate: today(),
      dueDate: "",
      description: "ERP invoice",
      currencyCode: "MYR",
      journalType: "SALES",
      currencyRate: 1,
      inclusiveTax: false,
      lines: [{ accNo: "500-0000", description: "Service charge", amount: 100, taxCode: "" }],
    }),
  },
  "ar-payments": {
    title: "AR Payments",
    singular: "AR Payment",
    label: "AR Payments",
    meta: "Customer receipts",
    icon: ReceiptText,
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Name"],
      ["description", "Description"],
      ["paymentMethod", "Method"],
      ["paymentAmt", "Payment", "money"],
      ["knockOffAmt", "Knock-off", "money"],
      ["unappliedAmount", "Unapplied", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Debtor Name"],
      ["description", "Description"],
      ["currencyCode", "Currency"],
      ["toDebtorRate", "Debtor Rate", "number"],
      ["toHomeRate", "Home Rate", "number"],
      ["paymentAmt", "Payment", "money"],
      ["localPaymentAmt", "Local Payment", "money"],
      ["knockOffAmt", "Knock-off", "money"],
      ["unappliedAmount", "Unapplied", "money"],
      ["refundAmount", "Refund", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
      ["cancelled", "Cancelled"],
      ["note", "Note"],
    ],
    paymentLineTitle: "Payment Lines",
    paymentLineColumns: [
      ["seq", "Seq"],
      ["paymentMethod", "Method"],
      ["paymentBy", "Pay By"],
      ["chequeNo", "Cheque No"],
      ["paymentAmt", "Payment", "money"],
      ["localPaymentAmt", "Local", "money"],
      ["bankCharge", "Bank Charge", "money"],
      ["isReturnedCheque", "RCHQ"],
    ],
    detailLineTitle: "Knock-off Invoices",
    detailLineColumns: [
      ["invoiceDocNo", "Invoice"],
      ["invoiceDate", "Date"],
      ["invoiceDescription", "Description"],
      ["invoiceTotal", "Invoice Total", "money"],
      ["amount", "Paid", "money"],
      ["discountAmount", "Discount", "money"],
      ["invoiceOutstanding", "Outstanding", "money"],
    ],
    formFields: [],
    lineFields: [],
  },
  "ar-deposits": {
    title: "AR Deposits",
    singular: "AR Deposit",
    label: "AR Deposits",
    meta: "Customer deposits",
    icon: ReceiptText,
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Name"],
      ["description", "Description"],
      ["paymentMethod", "Method"],
      ["paymentAmt", "Deposit", "money"],
      ["transferredAmt", "Transferred", "money"],
      ["outstanding", "Outstanding", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["cancelled", "Cancelled"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Debtor Name"],
      ["description", "Description"],
      ["depositPaymentMethod", "Deposit Method"],
      ["currencyCode", "Currency"],
      ["toDepositRate", "Deposit Rate", "number"],
      ["toHomeRate", "Home Rate", "number"],
      ["paymentAmt", "Deposit", "money"],
      ["transferredAmt", "Transferred", "money"],
      ["outstanding", "Outstanding", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["isSecurityDeposit", "Security Deposit"],
      ["cancelled", "Cancelled"],
      ["note", "Note"],
    ],
    paymentLineTitle: "Payment Lines",
    paymentLineColumns: [
      ["seq", "Seq"],
      ["paymentMethod", "Method"],
      ["paymentBy", "Pay By"],
      ["chequeNo", "Reference"],
      ["paymentAmt", "Payment", "money"],
      ["bankCharge", "Bank Charge", "money"],
      ["isReturnedCheque", "RCHQ"],
    ],
    detailLineTitle: "Applied AR Payments",
    detailLineColumns: [
      ["paymentDocNo", "Payment"],
      ["paymentDate", "Date"],
      ["paymentDescription", "Description"],
      ["paymentMethod", "Method"],
      ["amount", "Applied", "money"],
      ["localAmount", "Local", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
    ],
    refundLineTitle: "Refunds",
    refundLineColumns: [
      ["docNo", "Refund"],
      ["docDate", "Date"],
      ["name", "Name"],
      ["description", "Description"],
      ["refundAmt", "Refund", "money"],
      ["cashBookDocNo", "Cash Book"],
    ],
    forfeitLineTitle: "Forfeits",
    forfeitLineColumns: [
      ["docDate", "Date"],
      ["description", "Description"],
      ["forfeitedAccNo", "Account"],
      ["accountName", "Account Name"],
      ["forfeitedAmt", "Forfeited", "money"],
    ],
    formFields: [],
    lineFields: [],
  },
  "cash-book": {
    title: "Cash Book",
    singular: "Cash Book",
    label: "Cash Book",
    meta: "Bank and cash movement",
    icon: ReceiptText,
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["typeLabel", "Type"],
      ["sourceDocumentNo", "Source Doc"],
      ["dealWith", "Deal With"],
      ["description", "Description"],
      ["paymentMethod", "Method"],
      ["bankAccount", "Bank"],
      ["bankAmount", "Bank Amount", "money"],
      ["bankReconStatusLabel", "Recon"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["typeLabel", "Type"],
      ["sourceType", "Source Type"],
      ["sourceKey", "Source Key"],
      ["sourceDocumentLabel", "Source"],
      ["sourceDocumentNo", "Source Doc"],
      ["dealWith", "Deal With"],
      ["description", "Description"],
      ["currencyCode", "Currency"],
      ["currencyRate", "Rate", "number"],
      ["totalPayment", "Payment", "money"],
      ["localTotal", "Local Total", "money"],
      ["netTotal", "Net Total", "money"],
      ["localNetTotal", "Local Net", "money"],
      ["tax", "Tax", "money"],
      ["bankAccount", "Bank"],
      ["bankAccountName", "Bank Name"],
      ["bankAmount", "Bank Amount", "money"],
      ["bankReconStatusLabel", "Recon"],
      ["status", "Status"],
      ["cancelled", "Cancelled"],
    ],
    sourceDocumentTitle: "Source Documents",
    sourceDocumentColumns: [
      ["documentType", "Type"],
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["accountCode", "Account"],
      ["accountName", "Name"],
      ["description", "Description"],
      ["amount", "Amount", "money"],
      ["localAmount", "Local", "money"],
      ["status", "Status"],
    ],
    paymentLineTitle: "Payment Lines",
    paymentLineColumns: [
      ["seq", "Seq"],
      ["paymentMethod", "Method"],
      ["paymentBy", "Pay By"],
      ["chequeNo", "Reference"],
      ["paymentAmt", "Payment", "money"],
      ["bankCharge", "Bank Charge", "money"],
      ["isReturnedCheque", "RCHQ"],
    ],
    detailLineTitle: "GL Lines",
    detailLineColumns: [
      ["seq", "Seq"],
      ["accNo", "Account"],
      ["accountName", "Account Name"],
      ["description", "Description"],
      ["projNo", "Project"],
      ["deptNo", "Dept"],
      ["taxCode", "Tax"],
      ["amount", "Amount", "money"],
      ["localAmount", "Local", "money"],
    ],
    bankTransactionTitle: "Bank Transactions",
    bankTransactionColumns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["bankAccount", "Bank"],
      ["bankAccountName", "Bank Name"],
      ["description", "Description"],
      ["paymentAmt", "Amount", "money"],
      ["bankReconStatusLabel", "Recon"],
      ["bankStatementDate", "Statement Date"],
    ],
    formFields: [],
    lineFields: [],
  },
  "bank-transactions": {
    title: "Bank Transactions",
    singular: "Bank Transaction",
    label: "Bank Transactions",
    meta: "Bank reconciliation entries",
    icon: ReceiptText,
    rowKey: "bankTransKey",
    columns: [
      ["bankTransKey", "Key"],
      ["docDate", "Date"],
      ["bankAccount", "Bank"],
      ["bankAccountName", "Bank Name"],
      ["description", "Description"],
      ["docNo", "Cash Book"],
      ["sourceDocumentNo", "Source Doc"],
      ["bankAmount", "Amount", "money"],
      ["bankReconStatusLabel", "Recon"],
      ["bankStatementDate", "Statement Date"],
    ],
    detailFields: [
      ["bankTransKey", "Key"],
      ["docDate", "Date"],
      ["bankAccount", "Bank"],
      ["bankAccountName", "Bank Name"],
      ["description", "Description"],
      ["chequeNo", "Reference"],
      ["bankAmount", "Amount", "money"],
      ["bankReconStatusLabel", "Recon"],
      ["bankStatementDate", "Statement Date"],
      ["sourceType", "Source Type"],
      ["sourceKey", "Source Key"],
      ["docNo", "Cash Book Doc"],
      ["cashBookTypeLabel", "Cash Book Type"],
      ["sourceDocumentLabel", "Source"],
      ["sourceDocumentNo", "Source Doc"],
    ],
    sourceDocumentTitle: "Source Documents",
    sourceDocumentColumns: [
      ["documentType", "Type"],
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["description", "Description"],
      ["amount", "Amount", "money"],
    ],
    detailLineTitle: "Linked Cash Book",
    detailLineColumns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["typeLabel", "Type"],
      ["dealWith", "Deal With"],
      ["description", "Description"],
      ["totalPayment", "Payment", "money"],
      ["localTotal", "Local Total", "money"],
      ["status", "Status"],
    ],
    formFields: [],
    lineFields: [],
  },
  "ap-invoices": {
    title: "AP Invoices",
    singular: "AP Invoice",
    label: "AP Invoices",
    meta: "Supplier invoices",
    icon: ShoppingCart,
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Name"],
      ["supplierInvoiceNo", "Supplier Inv"],
      ["description", "Description"],
      ["netTotal", "Net Total", "money"],
      ["paymentAmt", "Paid", "money"],
      ["outstanding", "Outstanding", "money"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["dueDate", "Due Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Creditor Name"],
      ["supplierInvoiceNo", "Supplier Invoice"],
      ["description", "Description"],
      ["journalType", "Journal"],
      ["displayTerm", "Term"],
      ["currencyCode", "Currency"],
      ["currencyRate", "Rate", "number"],
      ["total", "Total", "money"],
      ["netTotal", "Net Total", "money"],
      ["paymentAmt", "Paid", "money"],
      ["outstanding", "Outstanding", "money"],
      ["status", "Status"],
      ["cancelled", "Cancelled"],
    ],
    paymentLineTitle: "AP Payments",
    paymentLineColumns: [
      ["paymentDocNo", "Payment"],
      ["paymentDate", "Date"],
      ["paymentDescription", "Description"],
      ["paymentMethod", "Method"],
      ["paymentTotal", "Payment Total", "money"],
      ["paidAmount", "Paid", "money"],
      ["discountAmount", "Discount", "money"],
      ["cashBookDocNo", "Cash Book"],
    ],
    detailLineTitle: "GL Lines",
    detailLineColumns: [
      ["seq", "Seq"],
      ["accNo", "Account"],
      ["accountName", "Account Name"],
      ["description", "Description"],
      ["projNo", "Project"],
      ["deptNo", "Dept"],
      ["taxCode", "Tax"],
      ["amount", "Amount", "money"],
      ["netAmount", "Net", "money"],
      ["knockOffAmount", "Knock-off", "money"],
    ],
    formFields: [],
    lineFields: [],
  },
  "ap-payments": {
    title: "AP Payments",
    singular: "AP Payment",
    label: "AP Payments",
    meta: "Supplier payments",
    icon: ReceiptText,
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Name"],
      ["description", "Description"],
      ["paymentMethod", "Method"],
      ["paymentAmt", "Payment", "money"],
      ["knockOffAmt", "Knock-off", "money"],
      ["unappliedAmount", "Unapplied", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Creditor Name"],
      ["description", "Description"],
      ["currencyCode", "Currency"],
      ["toCreditorRate", "Creditor Rate", "number"],
      ["toHomeRate", "Home Rate", "number"],
      ["paymentAmt", "Payment", "money"],
      ["localPaymentAmt", "Local Payment", "money"],
      ["knockOffAmt", "Knock-off", "money"],
      ["unappliedAmount", "Unapplied", "money"],
      ["refundAmount", "Refund", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
      ["cancelled", "Cancelled"],
      ["note", "Note"],
    ],
    paymentLineTitle: "Payment Lines",
    paymentLineColumns: [
      ["seq", "Seq"],
      ["paymentMethod", "Method"],
      ["paymentBy", "Pay By"],
      ["chequeNo", "Reference"],
      ["paymentAmt", "Payment", "money"],
      ["localPaymentAmt", "Local", "money"],
      ["bankCharge", "Bank Charge", "money"],
      ["isReturnedCheque", "RCHQ"],
    ],
    detailLineTitle: "Knock-off AP Invoices",
    detailLineColumns: [
      ["invoiceDocNo", "AP Invoice"],
      ["supplierInvoiceNo", "Supplier Inv"],
      ["invoiceDate", "Date"],
      ["invoiceDescription", "Description"],
      ["invoiceTotal", "Invoice Total", "money"],
      ["amount", "Paid", "money"],
      ["discountAmount", "Discount", "money"],
      ["invoiceOutstanding", "Outstanding", "money"],
    ],
    formFields: [],
    lineFields: [],
  },
  "ap-deposits": {
    title: "AP Deposits",
    singular: "AP Deposit",
    label: "AP Deposits",
    meta: "Supplier deposits",
    icon: ReceiptText,
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Name"],
      ["description", "Description"],
      ["paymentMethod", "Method"],
      ["paymentAmt", "Deposit", "money"],
      ["transferredAmt", "Transferred", "money"],
      ["outstanding", "Outstanding", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["cancelled", "Cancelled"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Creditor Name"],
      ["description", "Description"],
      ["depositPaymentMethod", "Deposit Method"],
      ["currencyCode", "Currency"],
      ["toDepositRate", "Deposit Rate", "number"],
      ["toHomeRate", "Home Rate", "number"],
      ["paymentAmt", "Deposit", "money"],
      ["transferredAmt", "Transferred", "money"],
      ["outstanding", "Outstanding", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["cancelled", "Cancelled"],
      ["note", "Note"],
    ],
    paymentLineTitle: "Payment Lines",
    paymentLineColumns: [
      ["seq", "Seq"],
      ["paymentMethod", "Method"],
      ["paymentBy", "Pay By"],
      ["chequeNo", "Reference"],
      ["paymentAmt", "Payment", "money"],
      ["bankCharge", "Bank Charge", "money"],
      ["isReturnedCheque", "RCHQ"],
    ],
    detailLineTitle: "Applied AP Payments",
    detailLineColumns: [
      ["paymentDocNo", "Payment"],
      ["paymentDate", "Date"],
      ["paymentDescription", "Description"],
      ["paymentMethod", "Method"],
      ["amount", "Applied", "money"],
      ["localAmount", "Local", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
    ],
    refundLineTitle: "Refunds",
    refundLineColumns: [
      ["docNo", "Refund"],
      ["docDate", "Date"],
      ["name", "Name"],
      ["description", "Description"],
      ["refundAmt", "Refund", "money"],
      ["cashBookDocNo", "Cash Book"],
    ],
    forfeitLineTitle: "Forfeits",
    forfeitLineColumns: [
      ["docDate", "Date"],
      ["description", "Description"],
      ["forfeitedAccNo", "Account"],
      ["accountName", "Account Name"],
      ["forfeitedAmt", "Forfeited", "money"],
    ],
    formFields: [],
    lineFields: [],
  },
  quotations: {
    title: "Quotations",
    singular: "Quotation",
    label: "Quotations",
    meta: "Sales quotation",
    icon: ClipboardList,
    createLabel: "New Draft",
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["description", "Description"],
      ["finalTotal", "Final Total", "money"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["debtorCode", "Debtor"],
      ["debtorName", "Debtor Name"],
      ["description", "Description"],
      ["agent", "Agent"],
      ["yourRef", "Reference"],
      ["paymentTerm", "Payment"],
      ["validity", "Validity"],
      ["currencyCode", "Currency"],
      ["currencyRate", "Rate", "number"],
      ["finalTotal", "Final Total", "money"],
      ["status", "Status"],
    ],
    detailLineColumns: [
      ["seq", "Seq"],
      ["itemCode", "Item"],
      ["description", "Description"],
      ["qty", "Qty", "number"],
      ["uom", "UOM"],
      ["unitPrice", "Unit Price", "number"],
      ["subTotal", "Subtotal", "number"],
    ],
    formFields: [
      { name: "debtorCode", label: "Debtor Code", required: true },
      { name: "docDate", label: "Doc Date", type: "date" },
      { name: "description", label: "Description", span: 2 },
      { name: "agent", label: "Agent" },
      { name: "yourRef", label: "Reference" },
      { name: "paymentTerm", label: "Payment Term" },
      { name: "validity", label: "Validity" },
      { name: "deliveryTerm", label: "Delivery Term" },
      { name: "currencyRate", label: "Currency Rate", ...MONEY },
      { name: "inclusiveTax", label: "Inclusive Tax", type: "checkbox" },
      { name: "transferable", label: "Transferable", type: "checkbox" },
    ],
    lineFields: [
      { name: "itemCode", label: "Item Code", required: true },
      { name: "description", label: "Description", span: 2 },
      { name: "qty", label: "Qty", ...QTY },
      { name: "uom", label: "UOM" },
      { name: "unitPrice", label: "Unit Price", ...MONEY },
      { name: "discount", label: "Discount" },
      { name: "taxCode", label: "Tax Code" },
    ],
    payload: () => ({
      debtorCode: "300-U001",
      docDate: today(),
      description: "ERP quotation",
      currencyCode: "MYR",
      agent: "ADMIN",
      yourRef: "",
      paymentTerm: "",
      validity: "",
      deliveryTerm: "",
      currencyRate: 1,
      inclusiveTax: false,
      transferable: true,
      lines: [{ itemCode: "00001", description: "", qty: 1, uom: "pcs", unitPrice: 392 }],
    }),
  },
  items: {
    title: "Items",
    singular: "Item",
    label: "Items",
    meta: "Stock item",
    icon: Package,
    createLabel: "New Item",
    rowKey: "itemCode",
    columns: [
      ["itemCode", "Item Code"],
      ["description", "Description"],
      ["baseUom", "Base UOM"],
      ["salesUom", "Sales UOM"],
      ["price", "Price", "number"],
      ["isActive", "Active"],
    ],
    detailFields: [
      ["itemCode", "Item Code"],
      ["description", "Description"],
      ["desc2", "Description 2"],
      ["itemGroup", "Group"],
      ["itemType", "Type"],
      ["itemBrand", "Brand"],
      ["itemCategory", "Category"],
      ["baseUom", "Base UOM"],
      ["salesUom", "Sales UOM"],
      ["purchaseUom", "Purchase UOM"],
      ["taxCode", "Sales Tax"],
      ["purchaseTaxCode", "Purchase Tax"],
      ["isActive", "Active"],
      ["discontinued", "Discontinued"],
    ],
    detailLineTitle: "UOM",
    detailLineColumns: [
      ["uom", "UOM"],
      ["rate", "Rate", "number"],
      ["price", "Price", "number"],
      ["cost", "Cost", "number"],
      ["barcode", "Barcode"],
    ],
    formFields: [
      { name: "itemCode", label: "Item Code", required: true },
      { name: "description", label: "Description", span: 2 },
      { name: "baseUom", label: "Base UOM" },
      { name: "salesUom", label: "Sales UOM" },
      { name: "purchaseUom", label: "Purchase UOM" },
      { name: "uomRate", label: "UOM Rate", ...QTY },
      { name: "price", label: "Price", ...MONEY },
      { name: "cost", label: "Cost", ...MONEY },
      { name: "itemGroup", label: "Group" },
      { name: "itemType", label: "Type" },
      { name: "itemBrand", label: "Brand" },
      { name: "itemCategory", label: "Category" },
      { name: "taxCode", label: "Sales Tax" },
      { name: "purchaseTaxCode", label: "Purchase Tax" },
      { name: "isActive", label: "Active", type: "checkbox" },
      { name: "isSalesItem", label: "Sales Item", type: "checkbox" },
      { name: "isPurchaseItem", label: "Purchase Item", type: "checkbox" },
      { name: "allowUpdate", label: "Allow Update", type: "checkbox" },
    ],
    lineFields: [],
    payload: () => ({
      itemCode: "ERP-ITEM-001",
      description: "ERP item",
      baseUom: "pcs",
      salesUom: "pcs",
      purchaseUom: "pcs",
      uomRate: 1,
      price: 392,
      cost: "",
      itemGroup: "",
      itemType: "",
      itemBrand: "",
      itemCategory: "",
      taxCode: "",
      purchaseTaxCode: "",
      isActive: true,
      isSalesItem: true,
      isPurchaseItem: true,
      allowUpdate: false,
    }),
  },
  "purchase-orders": {
    title: "Purchase Orders",
    singular: "Purchase Order",
    label: "Purchase Orders",
    meta: "Purchase order",
    icon: ShoppingCart,
    createLabel: "New Draft",
    rowKey: "docNo",
    columns: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["description", "Description"],
      ["finalTotal", "Final Total", "money"],
      ["status", "Status"],
    ],
    detailFields: [
      ["docNo", "Doc No"],
      ["docDate", "Date"],
      ["creditorCode", "Creditor"],
      ["creditorName", "Creditor Name"],
      ["description", "Description"],
      ["agent", "Agent"],
      ["currencyCode", "Currency"],
      ["currencyRate", "Rate", "number"],
      ["finalTotal", "Final Total", "money"],
      ["status", "Status"],
    ],
    detailLineColumns: [
      ["seq", "Seq"],
      ["itemCode", "Item"],
      ["description", "Description"],
      ["qty", "Qty", "number"],
      ["uom", "UOM"],
      ["unitPrice", "Unit Price", "number"],
      ["subTotal", "Subtotal", "number"],
    ],
    formFields: [
      { name: "creditorCode", label: "Creditor Code", required: true },
      { name: "docDate", label: "Doc Date", type: "date" },
      { name: "description", label: "Description", span: 2 },
      { name: "agent", label: "Agent" },
      { name: "currencyRate", label: "Currency Rate", ...MONEY },
      { name: "inclusiveTax", label: "Inclusive Tax", type: "checkbox" },
      { name: "transferable", label: "Transferable", type: "checkbox" },
    ],
    lineFields: [
      { name: "itemCode", label: "Item Code", required: true },
      { name: "description", label: "Description", span: 2 },
      { name: "qty", label: "Qty", ...QTY },
      { name: "uom", label: "UOM" },
      { name: "unitPrice", label: "Unit Price", ...MONEY },
      { name: "discount", label: "Discount" },
      { name: "taxCode", label: "Tax Code" },
    ],
    payload: () => ({
      creditorCode: "400-U001",
      docDate: today(),
      description: "ERP purchase order",
      currencyCode: "MYR",
      agent: "ADMIN",
      currencyRate: 1,
      inclusiveTax: false,
      transferable: true,
      lines: [{ itemCode: "00001", description: "", qty: 1, uom: "pcs", unitPrice: 100 }],
    }),
  },
  debtors: {
    title: "Debtors",
    singular: "Debtor",
    label: "Debtors",
    meta: "Customer account",
    icon: Users,
    rowKey: "debtorCode",
    columns: [
      ["debtorCode", "Debtor Code"],
      ["debtorName", "Debtor Name"],
      ["displayTerm", "Term"],
      ["currencyCode", "Currency"],
      ["agent", "Agent"],
      ["phone", "Phone"],
    ],
    detailFields: [
      ["debtorCode", "Debtor Code"],
      ["debtorName", "Debtor Name"],
      ["displayTerm", "Term"],
      ["currencyCode", "Currency"],
      ["agent", "Agent"],
      ["area", "Area"],
      ["phone", "Phone"],
      ["email", "Email"],
      ["creditLimit", "Credit Limit", "number"],
    ],
    detailLineColumns: [],
    formFields: [],
    lineFields: [],
  },
  creditors: {
    title: "Creditors",
    singular: "Creditor",
    label: "Creditors",
    meta: "Supplier account",
    icon: Users,
    rowKey: "creditorCode",
    columns: [
      ["creditorCode", "Creditor Code"],
      ["creditorName", "Creditor Name"],
      ["displayTerm", "Term"],
      ["currencyCode", "Currency"],
      ["agent", "Agent"],
      ["phone", "Phone"],
      ["invoiceCount", "AP Invoices", "number"],
      ["outstanding", "Outstanding", "money"],
    ],
    detailFields: [
      ["creditorCode", "Creditor Code"],
      ["creditorName", "Creditor Name"],
      ["displayTerm", "Term"],
      ["currencyCode", "Currency"],
      ["agent", "Agent"],
      ["area", "Area"],
      ["phone", "Phone"],
      ["email", "Email"],
      ["creditLimit", "Credit Limit", "money"],
      ["invoiceCount", "AP Invoices", "number"],
      ["outstanding", "Outstanding", "money"],
      ["isActive", "Active"],
    ],
    paymentLineTitle: "AP Payments",
    paymentLineColumns: [
      ["docNo", "Payment"],
      ["docDate", "Date"],
      ["description", "Description"],
      ["paymentAmt", "Payment", "money"],
      ["knockOffAmt", "Knock-off", "money"],
      ["unappliedAmount", "Unapplied", "money"],
      ["cashBookDocNo", "Cash Book"],
      ["status", "Status"],
    ],
    detailLineTitle: "AP Invoices",
    detailLineColumns: [
      ["docNo", "AP Invoice"],
      ["docDate", "Date"],
      ["supplierInvoiceNo", "Supplier Inv"],
      ["description", "Description"],
      ["netTotal", "Net Total", "money"],
      ["paymentAmt", "Paid", "money"],
      ["outstanding", "Outstanding", "money"],
      ["status", "Status"],
    ],
    formFields: [],
    lineFields: [],
  },
  "rdp-allow": {
    title: "Allow IP for RDP",
    label: "Allow IP for RDP",
    meta: "Remote Desktop firewall",
    icon: ShieldCheck,
    system: true,
  },
  employees: {
    title: "Employees",
    editable: true,
    singular: "Employee",
    label: "Employees",
    meta: "Seng Chong staff",
    icon: Contact,
    createLabel: "New Employee",
    rowKey: "employeeCode",
    columns: [
      ["employeeCode", "Code"],
      ["name", "Name"],
      ["position", "Position"],
      ["phone", "Phone"],
      ["status", "Status"],
      ["username", "ERP Login"],
      ["userRole", "Login Role"],
      ["hiredOn", "Hired"],
    ],
    detailFields: [
      ["employeeCode", "Code"],
      ["name", "Name"],
      ["position", "Position"],
      ["status", "Status"],
      ["phone", "Phone"],
      ["email", "Email"],
      ["icNo", "IC / Passport"],
      ["hiredOn", "Hired On"],
      ["leftOn", "Left On"],
      ["username", "ERP Login"],
      ["userDisplayName", "Login Display Name"],
      ["userRole", "Login Role"],
      ["notes", "Notes"],
      ["createdBy", "Created By"],
      ["updatedBy", "Updated By"],
    ],
    detailLineColumns: [],
    formFields: [
      // No employee code field: the system issues it on create and it never
      // changes. It still shows in the list and on the detail page.
      { name: "name", label: "Name", required: true, span: 2 },
      { name: "position", label: "Position", type: "select", options: EMPLOYEE_POSITIONS },
      { name: "status", label: "Status", type: "select", options: EMPLOYEE_STATUSES },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email" },
      { name: "icNo", label: "IC / Passport" },
      { name: "hiredOn", label: "Hired On", type: "date" },
      { name: "leftOn", label: "Left On", type: "date" },
      // Optional: most of the crew never sign in. Leave blank for no login.
      { name: "username", label: "ERP Login (optional)" },
      { name: "notes", label: "Notes", type: "textarea", span: 2, rows: 3 },
    ],
    lineFields: [],
    payload: () => ({
      name: "",
      position: EMPLOYEE_POSITIONS[0],
      status: EMPLOYEE_STATUSES[0],
      phone: "",
      email: "",
      icNo: "",
      hiredOn: "",
      leftOn: "",
      username: "",
      notes: "",
      lines: [],
    }),
  },
  salary: {
    title: "Salary Setup",
    editable: true,
    singular: "Salary",
    label: "Salary Setup",
    meta: "Pay and statutory details (admin only)",
    icon: Banknote,
    // Rows are created from the employee list, so there is no "New" button:
    // every active employee already appears, set up or not.
    rowKey: "employeeCode",
    columns: [
      ["employeeCode", "Code"],
      ["name", "Name"],
      ["position", "Position"],
      ["payType", "Pay Type"],
      ["basicRate", "Basic", "money"],
      ["otRuleText", "OT / Overnight Rule"],
      ["fixedAllowance", "Allowance", "money"],
      ["epfMemberNo", "EPF No"],
      ["socsoNo", "SOCSO No"],
      ["bankName", "Bank"],
    ],
    detailFields: [
      ["employeeCode", "Code"],
      ["name", "Name"],
      ["position", "Position"],
      ["status", "Employee Status"],
      ["payType", "Pay Type"],
      ["basicRate", "Basic Rate", "money"],
      ["otRuleText", "OT / Overnight Rule"],
      ["otDivisor", "OT Divisor"],
      ["otMultiplier", "OT Multiplier"],
      ["overnightMode", "Overnight Mode"],
      ["overnightAllowance", "Overnight Allowance", "money"],
      ["overnightMultiplier", "Overnight Multiplier"],
      ["overnightDayFactor", "Overnight Day Factor"],
      ["fixedAllowance", "Fixed Allowance", "money"],
      ["allowanceNote", "Allowance Note"],
      ["effectiveFrom", "Effective From"],
      ["epfMemberNo", "EPF Member No"],
      ["epfContributing", "EPF Contributing"],
      ["socsoNo", "SOCSO No"],
      ["socsoContributing", "SOCSO Contributing"],
      ["taxNo", "Income Tax No"],
      ["bankName", "Bank"],
      ["bankAccountNo", "Bank Account"],
      ["notes", "Notes"],
      ["updatedBy", "Updated By"],
    ],
    detailLineColumns: [],
    formFields: [
      { name: "payType", label: "Pay Type", type: "select", options: PAY_TYPES },
      { name: "basicRate", label: "Basic Rate", ...MONEY },
      { name: "fixedAllowance", label: "Fixed Allowance", ...MONEY },
      { name: "allowanceNote", label: "Allowance Note", span: 2 },
      { name: "effectiveFrom", label: "Effective From", type: "date" },
      // OT hourly base = basic rate / divisor. The divisor is this person's
      // standard hours: 8, 9 and 10 are all in use, each with its own
      // multiplier, so both are per person.
      { name: "otDivisor", label: "OT Divisor (std hours/day)", type: "number", step: "0.5" },
      { name: "otMultiplier", label: "OT Multiplier", type: "number", step: "0.05" },
      { name: "overnightMode", label: "Overnight Mode", type: "select", options: OVERNIGHT_MODES },
      { name: "overnightAllowance", label: "Overnight Allowance / night", ...MONEY },
      { name: "overnightMultiplier", label: "Overnight Multiplier (hourly mode)", type: "number", step: "0.05" },
      { name: "overnightDayFactor", label: "Overnight Day Factor (extra-day mode)", type: "number", step: "0.05" },
      { name: "epfMemberNo", label: "EPF Member No" },
      { name: "epfContributing", label: "EPF Contributing", type: "checkbox" },
      { name: "socsoNo", label: "SOCSO No" },
      { name: "socsoContributing", label: "SOCSO Contributing", type: "checkbox" },
      { name: "taxNo", label: "Income Tax No" },
      { name: "bankName", label: "Bank" },
      { name: "bankAccountNo", label: "Bank Account No" },
      { name: "notes", label: "Notes", type: "textarea", span: 2, rows: 3 },
    ],
    lineFields: [],
  },
  "work-entries": {
    title: "Timesheet",
    singular: "Work Entry",
    label: "Timesheet",
    meta: "Attendance, OT and overnight (admin only)",
    icon: CalendarClock,
    editable: true,
    createLabel: "New Work Entry",
    rowKey: "id",
    columns: [
      ["workDate", "Date"],
      ["employeeCode", "Code"],
      ["name", "Name"],
      ["company", "Company"],
      ["projectCode", "Project"],
      ["dayUnits", "Days"],
      ["otHours", "OT Hrs"],
      ["overnightNights", "Nights"],
      ["normalPay", "Normal", "money"],
      ["otPay", "OT", "money"],
      ["overnightPay", "Overnight", "money"],
      ["totalPay", "Total", "money"],
    ],
    detailFields: [
      ["workDate", "Date"],
      ["employeeCode", "Employee Code"],
      ["name", "Name"],
      ["position", "Position"],
      ["company", "Company"],
      ["projectCode", "Project"],
      ["projectTitle", "Project Title"],
      ["dayUnits", "Day Units"],
      ["otHours", "OT Hours"],
      ["overnightNights", "Overnight Nights"],
      ["overnightHours", "Overnight Hours"],
      ["dailyRate", "Daily Rate", "money"],
      ["normalPay", "Normal Pay", "money"],
      ["otPay", "OT Pay", "money"],
      ["overnightPay", "Overnight Pay", "money"],
      ["totalPay", "Total Pay", "money"],
      ["payableNote", "Note"],
      ["note", "Remark"],
      ["updatedBy", "Updated By"],
    ],
    detailLineColumns: [],
    formFields: [
      { name: "employeeCode", label: "Employee Code", required: true },
      { name: "workDate", label: "Date", type: "date", required: true },
      { name: "company", label: "Company" },
      // Optional: shop tidying and errands belong to no single job.
      { name: "projectCode", label: "Project Code (optional)" },
      { name: "dayUnits", label: "Day Units", type: "number", step: "0.25" },
      { name: "otHours", label: "OT Hours", type: "number", step: "0.25" },
      { name: "overnightNights", label: "Overnight Nights", type: "number", step: "1" },
      { name: "overnightHours", label: "Overnight Hours", type: "number", step: "0.25" },
      { name: "note", label: "Remark", type: "textarea", span: 2, rows: 2 },
    ],
    lineFields: [],
    payload: () => ({
      employeeCode: "",
      workDate: today(),
      company: "",
      projectCode: "",
      dayUnits: "1",
      otHours: "",
      overnightNights: "",
      overnightHours: "",
      note: "",
      lines: [],
    }),
  },
  "work-day-sheet": {
    title: "Daily Entry",
    label: "Daily Entry",
    meta: "Record the whole crew for one day",
    icon: CalendarClock,
    system: true,
  },
  "user-management": {
    title: "User Management",
    label: "User Management",
    meta: "ERP login users",
    icon: Users,
    system: true,
  },
  "website-content": {
    title: "Website Content",
    label: "Website Content",
    meta: "sengchong.com public content",
    icon: ImageIcon,
    system: true,
  },
};
